<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>disable</Nullable>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\MitsubishiLaserMES.Core\MitsubishiLaserMES.Core.csproj" />
    <ProjectReference Include="..\MitsubishiLaser.Simulator\MitsubishiLaser.Simulator.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="Protocol.Core">
      <HintPath>..\..\dll\Protocol.Core.dll</HintPath>
    </Reference>
  </ItemGroup>

  <ItemGroup>
    <None Update="appsettings.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Include="..\..\Dictionaries\**\*.*">
      <Link>Dictionaries\%(RecursiveDir)%(FileName)%(Extension)</Link>
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Include="..\..\dll\Protocol.Core.dll">
      <Link>Protocol.Core.dll</Link>
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>

</Project>