<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <AssemblyName>EQSimulator</AssemblyName>
    <RootNamespace>EQSimulator</RootNamespace>
    <LangVersion>latest</LangVersion>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <GenerateTargetFrameworkAttribute>false</GenerateTargetFrameworkAttribute>
    <ApplicationIcon>EQ.ico</ApplicationIcon>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="bin\**;obj\**" />
    <None Remove="bin\**;obj\**" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="EQ.ico" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\CyntecMqttLib\CyntecMqttLib.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="Protocol.Core">
      <HintPath>..\dll\Protocol.Core.dll\Protocol.Core.dll</HintPath>
    </Reference>
  </ItemGroup>

  <ItemGroup>
    <None Include="..\Dictionaries\*.json">
      <Link>Dictionaries\%(Filename)%(Extension)</Link>
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>
</Project>
